"""
export_generator.py — Enterprise Configuration & Automation Exporters
Generates Cisco IOS-XE configs, Terraform HCL, Ansible playbooks, and IPAM/BOM reports.
"""

from typing import Dict, List
import json
from network_models import NetworkNode, NetworkLink, NetworkTier, DeviceType, TopologyMetrics


class ExportGenerator:
    """Generates industry-standard network configs and automation scripts."""

    @staticmethod
    def generate_cisco_ios_config(nodes: Dict[str, NetworkNode], links: List[NetworkLink], vlans: List) -> str:
        """Generate combined Cisco IOS-XE configuration for key devices."""
        cfg = []
        cfg.append("! ========================================================")
        cfg.append("! AUTOMATIC NETWORK TOPOLOGY CONFIGURATION")
        cfg.append("! Generated by Generative AI Topology Designer")
        cfg.append("! Target Platform: Cisco IOS-XE / Catalyst Enterprise")
        cfg.append("! ========================================================\n")

        # Global VLAN database
        cfg.append("! --- Global VLAN Configuration ---")
        for v in vlans:
            cfg.append(f"vlan {v.vlan_id}")
            cfg.append(f" name {v.name}")
        cfg.append("exit\n")

        # Device specific configurations
        for node in nodes.values():
            cfg.append(f"! --------------------------------------------------------")
            cfg.append(f"! Hostname: {node.id.upper()} ({node.label.replace(chr(10), ' ')})")
            cfg.append(f"! Role: {node.tier.value} | Model: {node.device_spec.model if node.device_spec else 'Standard'}")
            cfg.append(f"! --------------------------------------------------------")
            cfg.append(f"hostname {node.id.upper()}")
            cfg.append("service password-encryption")
            cfg.append("no ip domain-lookup")
            cfg.append("spanning-tree mode rapid-pvst")
            cfg.append("spanning-tree portfast default")
            cfg.append("spanning-tree bpduguard default")

            # Management & IP
            cfg.append("interface Loopback0")
            cfg.append(f" description Management Loopback")
            cfg.append(f" ip address {node.ip_address} 255.255.255.255")
            cfg.append(" no shutdown")

            # Connected interfaces
            connected_links = [l for l in links if l.source == node.id or l.target == node.id]
            port_num = 1
            for l in connected_links:
                peer_id = l.target if l.source == node.id else l.source
                cfg.append(f"interface GigabitEthernet1/0/{port_num}")
                cfg.append(f" description Link to {peer_id.upper()} [{l.bandwidth_gbps}Gbps - {l.protocol or 'Trunk'}]")
                if node.tier in (NetworkTier.CORE, NetworkTier.DISTRIBUTION):
                    cfg.append(" switchport mode trunk")
                    cfg.append(f" switchport trunk allowed vlan {','.join(str(v.vlan_id) for v in vlans)}")
                else:
                    if node.vlan_ids:
                        cfg.append(f" switchport mode access")
                        cfg.append(f" switchport access vlan {node.vlan_ids[0]}")
                    else:
                        cfg.append(" switchport mode trunk")
                cfg.append(" no shutdown")
                port_num += 1

            # Routing protocol if Core / Distribution
            if node.tier in (NetworkTier.CORE, NetworkTier.DISTRIBUTION):
                cfg.append("router ospf 1")
                cfg.append(f" router-id {node.ip_address}")
                cfg.append(" network 10.0.0.0 0.255.255.255 area 0")
                cfg.append(" passive-interface default")
                for p in range(1, port_num):
                    cfg.append(f" no passive-interface GigabitEthernet1/0/{p}")

            cfg.append("exit\n")

        return "\n".join(cfg)

    @staticmethod
    def generate_terraform(nodes: Dict[str, NetworkNode], vlans: List) -> str:
        """Generate Terraform HCL for Cloud / Hybrid Network Architecture."""
        tf = []
        tf.append('terraform {')
        tf.append('  required_version = ">= 1.5.0"')
        tf.append('  required_providers {')
        tf.append('    aws = {')
        tf.append('      source  = "hashicorp/aws"')
        tf.append('      version = "~> 5.0"')
        tf.append('    }')
        tf.append('  }')
        tf.append('}\n')
        tf.append('provider "aws" {')
        tf.append('  region = "us-east-1"')
        tf.append('}\n')
        tf.append('# Enterprise Backbone VPC')
        tf.append('resource "aws_vpc" "enterprise_backbone" {')
        tf.append('  cidr_block           = "10.0.0.0/16"')
        tf.append('  enable_dns_hostnames = true')
        tf.append('  enable_dns_support   = true')
        tf.append('  tags = {')
        tf.append('    Name        = "Enterprise-AI-Backbone"')
        tf.append('    Environment = "Production"')
        tf.append('  }')
        tf.append('}\n')

        # Subnets for each VLAN
        for idx, v in enumerate(vlans):
            clean_name = v.name.lower().replace(" ", "_").replace("-", "_")
            tf.append(f'# Subnet for {v.name}')
            tf.append(f'resource "aws_subnet" "{clean_name}" {{')
            tf.append('  vpc_id            = aws_vpc.enterprise_backbone.id')
            tf.append(f'  cidr_block        = "{v.subnet}"')
            tf.append(f'  availability_zone = "us-east-1a"')
            tf.append('  tags = {')
            tf.append(f'    Name    = "{v.name}-VLAN{v.vlan_id}"')
            tf.append(f'    Purpose = "{v.purpose}"')
            tf.append('  }')
            tf.append('}\n')

        # Security Group
        tf.append('resource "aws_security_group" "core_sg" {')
        tf.append('  name        = "enterprise-core-security-group"')
        tf.append('  description = "Managed by Generative AI Topology Optimizer"')
        tf.append('  vpc_id      = aws_vpc.enterprise_backbone.id')
        tf.append('  ingress {')
        tf.append('    description = "Internal Enterprise Subnets"')
        tf.append('    from_port   = 0')
        tf.append('    to_port     = 0')
        tf.append('    protocol    = "-1"')
        tf.append('    cidr_blocks = ["10.0.0.0/16"]')
        tf.append('  }')
        tf.append('  egress {')
        tf.append('    from_port   = 0')
        tf.append('    to_port     = 0')
        tf.append('    protocol    = "-1"')
        tf.append('    cidr_blocks = ["0.0.0.0/0"]')
        tf.append('  }')
        tf.append('}')

        return "\n".join(tf)

    @staticmethod
    def generate_ansible_playbook(nodes: Dict[str, NetworkNode]) -> str:
        """Generate Ansible automation playbook to provision topology switches."""
        playbook = [
            "---",
            "- name: Enterprise Network Topology Orchestration",
            "  hosts: network_switches",
            "  gather_facts: no",
            "  connection: network_cli",
            "  vars:",
            "    ansible_network_os: cisco.ios.ios",
            "  tasks:",
            "    - name: Ensure Base Hostname and Banner Configuration",
            "      cisco.ios.ios_banner:",
            "        banner: motd",
            "        text: |",
            "          *************************************************",
            "          * AUTHORIZED ACCESS ONLY — ENTERPRISE TOPOLOGY  *",
            "          * Provisioned via Generative AI Network Engine  *",
            "          *************************************************",
            "        state: present",
            "",
            "    - name: Configure Logging and NTP Infrastructure",
            "      cisco.ios.ios_logging_global:",
            "        config:",
            "          hosts:",
            "            - host: 10.0.100.10",
            "          trap: informational",
            "",
            "    - name: Enable Rapid Per-VLAN Spanning Tree",
            "      cisco.ios.ios_config:",
            "        lines:",
            "          - spanning-tree mode rapid-pvst",
            "          - spanning-tree extend system-id",
            "",
            "    - name: Save Running Configuration to Startup",
            "      cisco.ios.ios_config:",
            "        save_when: modified",
        ]
        return "\n".join(playbook)

    @staticmethod
    def generate_ipam_json(nodes: Dict[str, NetworkNode], vlans: List) -> str:
        """Generate IP Address Management (IPAM) JSON export."""
        data = {
            "enterprise_ipam": {
                "vlans": [
                    {
                        "vlan_id": v.vlan_id,
                        "name": v.name,
                        "subnet": v.subnet,
                        "gateway": v.gateway,
                        "purpose": v.purpose,
                    }
                    for v in vlans
                ],
                "devices": [
                    {
                        "id": n.id,
                        "label": n.label.replace("\n", " - "),
                        "tier": n.tier.value,
                        "ip_address": n.ip_address,
                        "subnet": n.subnet,
                        "model": n.device_spec.model if n.device_spec else "Virtual Gateway",
                        "ports_1g": n.device_spec.ports_1g if n.device_spec else 0,
                        "ports_10g": n.device_spec.ports_10g if n.device_spec else 0,
                        "vlan_ids": n.vlan_ids,
                    }
                    for n in nodes.values()
                ]
            }
        }
        return json.dumps(data, indent=2)
